### ISSUE TITLE
[Meeting] 03/25/2022

### ISSUE THREAD

**Issue by yehyunsuh** [yehyunsuh/TEM-Image-Segmentation#1]
## What
First meeting

## Why
- Talk about data scaling & analysis
- Setup all the collaboration tools
- Setup milestones for the project

## How
- [x] Share Notion Page 
- [x] Create Wandb team 
- [x] #2
- [x] Create Slack Channel - free version of slack deletes chats after 90days, but we can connect it with wandb. maybe use slack for wandb & use another chatting application that does not delete chats
For example, Microsoft Teams, Google Chat, Discord, etc

**Comment by yehyunsuh** [comment]
서예현
- W&B: yehyun-suh
- Slack: yehyun.suh@vanderbilt.edu

**Comment by Huijin-An** [comment]
안희진

- W&B: huijin-an
- slack: huijin.an@vanderbilt.edu
- Notion: hijin0848@gmail.com

**Comment by YJY189** [comment]
윤종연

- W&B: jongyeon-yoon
- slack: jongyeon.yoon97@gmail.com
- Notion: yjongy97@dgu.ac.kr

**Comment by yehyunsuh** [comment]
Notion page shared, wandb team created, chose to use PyCharm #2 , slack for wandb notification & kakaotalk for team work. Close Issue.
